words ={
  "achieve": "erishmoq",
  "adapt": "moslashmoq",
  "admire": "hayratlanmoq",
  "admit": "tan olmoq",
  "affect": "ta’sir qilmoq",
  "analyze": "tahlil qilmoq",
  "announce": "e’lon qilmoq",
  "approach": "yondashuv",
  "argue": "bahslashmoq",
  "arrange": "tashkil qilmoq",
  "assume": "faraz qilmoq",
  "attempt": "urinish",
  "avoid": "qochmoq",
  "aware": "xabardor",
  "balance": "muvozanat",
  "benefit": "foyda",
  "challenge": "qiyinchilik",
  "claim": "da’vo qilmoq",
  "compare": "taqqoslamoq",
  "complain": "shikoyat qilmoq",
  "concentrate": "diqqatni jamlamoq",
  "concern": "tashvish",
  "confirm": "tasdiqlamoq",
  "connect": "bog‘lamoq",
  "consider": "hisobga olmoq",
  "contain": "o‘z ichiga olmoq",
  "contribute": "hissa qo‘shmoq",
  "convince": "ishontirmoq",
  "cope": "uddalamoq",
  "create": "yaratmoq",
  "criticize": "tanqid qilmoq",
  "decision": "qaror",
  "demand": "talab",
  "describe": "tasvirlamoq",
  "design": "loyiha",
  "develop": "rivojlantirmoq",
  "disagree": "rozi bo‘lmaslik",
  "discover": "kashf qilmoq",
  "discuss": "muhokama qilmoq",
  "doubt": "shubha",
  "effective": "samarali",
  "encourage": "rag‘batlantirmoq",
  "environment": "atrof-muhit",
  "establish": "asos solmoq",
  "estimate": "taxmin qilmoq",
  "evidence": "dalil",
  "experience": "tajriba",
  "explain": "tushuntirmoq",
  "express": "ifodalamoq",
  "fail": "muvaffaqiyatsizlikka uchramoq",
  "feature": "xususiyat",
  "focus": "e’tibor qaratmoq",
  "force": "majbur qilmoq",
  "freedom": "erkinlik",
  "function": "vazifa",
  "generate": "yaratmoq",
  "goal": "maqsad",
  "handle": "hal qilmoq",
  "harm": "zarar",
  "improve": "yaxshilamoq",
  "include": "o‘z ichiga olmoq",
  "increase": "oshirmoq",
  "influence": "ta’sir",
  "inform": "xabardor qilmoq",
  "intend": "niyat qilmoq",
  "involve": "jalb qilmoq",
  "issue": "muammo",
  "knowledge": "bilim",
  "limit": "chegara",
  "maintain": "saqlab qolmoq",
  "manage": "boshqarmoq",
  "measure": "o‘lchamoq",
  "method": "usul",
  "motivate": "rag‘batlantirmoq",
  "negotiate": "muzokara qilmoq",
  "observe": "kuzatmoq",
  "opportunity": "imkoniyat",
  "organize": "tashkil qilmoq",
  "participate": "qatnashmoq",
  "persuade": "ko‘ndirmoq",
  "predict": "bashorat qilmoq",
  "prefer": "afzal ko‘rmoq",
  "prepare": "tayyorlamoq",
  "prevent": "oldini olmoq",
  "process": "jarayon",
  "produce": "ishlab chiqarmoq",
  "progress": "taraqqiyot",
  "protect": "himoya qilmoq",
  "provide": "ta’minlamoq",
  "purpose": "maqsad",
  "react": "munosabat bildirmoq",
  "realize": "anglamoq",
  "recognize": "tanimoq",
  "reduce": "kamaytirmoq",
  "reflect": "aks ettirmoq",
  "refuse": "rad etmoq",
  "require": "talab qilmoq",
  "research": "tadqiqot",
  "respond": "javob bermoq",
  "result": "natija",
  "risk": "xavf",
  "role": "rol",
  "satisfy": "qoniqtirmoq",
  "schedule": "jadval",
  "select": "tanlamoq",
  "significant": "ahamiyatli",
  "solution": "yechim",
  "strategy": "strategiya",
  "strength": "kuch",
  "stress": "bosim",
  "succeed": "muvaffaqiyatga erishmoq",
  "suggest": "taklif qilmoq",
  "support": "qo‘llab-quvvatlamoq",
  "survive": "omon qolmoq",
  "target": "nishon",
  "tend": "moyil bo‘lmoq",
  "theory": "nazariya",
  "threat": "tahdid",
  "tradition": "an’ana",
  "transform": "o‘zgartirmoq",
  "treat": "munosabatda bo‘lmoq",
  "trend": "tendensiya",
  "trust": "ishonch",
  "understand": "tushunmoq",
  "unique": "noyob",
  "value": "qadriyat",
  "variety": "xilma-xillik",
  "volunteer": "ko‘ngilli",
  "waste": "isrof",
  "wealth": "boylik",
  "willing": "tayyor",
  "worry": "xavotir",
  "achievable": "erishish mumkin bo‘lgan",
  "reasonable": "asosli",
  "reliable": "ishonchli",
  "responsible": "mas’ul",
  "significantly": "sezilarli darajada",
  "ultimately": "oxir-oqibat"
}